# 0.&nbsp;Setup Environment

## 0.1 Install Packages

In [ ]:
!pip install --quiet duckdb
!pip install --quiet jupysql
!pip install --quiet duckdb-engine

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.7/80.7 kB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.1/292.1 kB 9.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 48.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 kB 1.7 MB/s eta 0:00:00

## 0.2 Connect G-Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
default_dir = "/content/drive/MyDrive/00. Digital Skola/H1 2022/4. SQL II"
os.chdir(default_dir)

In [ ]:
!ls

 Alternative				        Homework
 chinook.db				       'Quiz - SQL II.docx'
 ERD_Relationship_Symbols_Quick_Reference.pdf  '[Sandbox] SQL - Part II.ipynb'
'[For Tutor] SQL - Part II.ipynb'	       'SQL II (Intermediate).pptx'

## 0.3 Library Import and Configuration

In [ ]:
import duckdb
import pandas as pd
# No need to import sqlalchemy or duckdb_engine
# JupySQL will use SQLAlchemy to auto-detect the driver needed based on your connection string!

# Import jupysql Jupyter extension to create SQL cells
%load_ext sql

We configure jupysql to return data as a Pandas dataframe and have less verbose output

In [ ]:
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

## 0.4 Connecting to a SQLite DB
Connect jupysql to DuckDB using a SQLAlchemy-style connection string. You may either connect to an in memory DuckDB, or a file backed db.

In [ ]:
%sql duckdb:///:memory:

In [ ]:
%%sql
SELECT
  'Off and flying!' AS a_duckdb_column

   a_duckdb_column
0  Off and flying!

In [ ]:
%%sql
INSTALL sqlite;
LOAD sqlite;

Empty DataFrame
Columns: [Success]
Index: []

In [ ]:
conn = duckdb.connect('chinook.db')

# 1.&nbsp;Explore The Database

In [ ]:
conn.sql("SHOW ALL TABLES")

┌──────────┬─────────┬─────────────────┬──────────────────────┬────────────────────────────────────────────┬───────────┐
│ database │ schema  │      name       │     column_names     │                column_types                │ temporary │
│ varchar  │ varchar │     varchar     │      varchar[]       │                 varchar[]                  │  boolean  │
├──────────┼─────────┼─────────────────┼──────────────────────┼────────────────────────────────────────────┼───────────┤
│ chinook  │ main    │ albums          │ [AlbumId, Title, A…  │ [BIGINT, VARCHAR, BIGINT]                  │ false     │
│ chinook  │ main    │ artists         │ [ArtistId, Name]     │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ customers       │ [CustomerId, First…  │ [BIGINT, VARCHAR, VARCHAR, VARCHAR, VARC…  │ false     │
│ chinook  │ main    │ employees       │ [EmployeeId, LastN…  │ [BIGINT, VARCHAR, VARCHAR, VARCHAR, BIGI…  │ false     │
│ chinook  │ main    │ genres          │ [GenreId, Name]      │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ invoice_items   │ [InvoiceLineId, In…  │ [BIGINT, BIGINT, BIGINT, DOUBLE, BIGINT]   │ false     │
│ chinook  │ main    │ invoices        │ [InvoiceId, Custom…  │ [BIGINT, BIGINT, TIMESTAMP, VARCHAR, VAR…  │ false     │
│ chinook  │ main    │ media_types     │ [MediaTypeId, Name]  │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ playlist_track  │ [PlaylistId, Track…  │ [BIGINT, BIGINT]                           │ false     │
│ chinook  │ main    │ playlists       │ [PlaylistId, Name]   │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ sqlite_sequence │ [name, seq]          │ [BLOB, BLOB]                               │ false     │
│ chinook  │ main    │ sqlite_stat1    │ [tbl, idx, stat]     │ [BLOB, BLOB, BLOB]                         │ false     │
│ chinook  │ main    │ tracks          │ [TrackId, Name, Al…  │ [BIGINT, VARCHAR, BIGINT, BIGINT, BIGINT…  │ false     │
├──────────┴─────────┴─────────────────┴──────────────────────┴────────────────────────────────────────────┴───────────┤
│ 13 rows                                                                                                    6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [ ]:
conn.sql("DESCRIBE albums")

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬───────┐
│ column_name │ column_type │  null   │   key   │ default │ extra │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ int32 │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼───────┤
│ AlbumId     │ BIGINT      │ NO      │ NULL    │ NULL    │  NULL │
│ Title       │ VARCHAR     │ NO      │ NULL    │ NULL    │  NULL │
│ ArtistId    │ BIGINT      │ NO      │ NULL    │ NULL    │  NULL │
└─────────────┴─────────────┴─────────┴─────────┴─────────┴───────┘

In [ ]:
%config SqlMagic.displaycon = True

In [ ]:
%sql duckdb:///chinook.db

In [ ]:
%sql SELECT * FROM customers LIMIT 10;

Running query in 'duckdb:///chinook.db'

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,0171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5
6,7,Astrid,Gruber,NaN,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,NaN,Austria,1010,+43 01 5134505,NaN,astrid.gruber@apple.at,5
7,8,Daan,Peeters,NaN,Grétrystraat 63,Brussels,NaN,Belgium,1000,+32 02 219 03 03,NaN,daan_peeters@apple.be,4
8,9,Kara,Nielsen,NaN,Sønder Boulevard 51,Copenhagen,NaN,Denmark,1720,+453 3331 9991,NaN,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4

In [ ]:
conn.sql('DESCRIBE customers')

┌──────────────┬─────────────┬─────────┬─────────┬─────────┬───────┐
│ column_name  │ column_type │  null   │   key   │ default │ extra │
│   varchar    │   varchar   │ varchar │ varchar │ varchar │ int32 │
├──────────────┼─────────────┼─────────┼─────────┼─────────┼───────┤
│ CustomerId   │ BIGINT      │ NO      │ NULL    │ NULL    │  NULL │
│ FirstName    │ VARCHAR     │ NO      │ NULL    │ NULL    │  NULL │
│ LastName     │ VARCHAR     │ NO      │ NULL    │ NULL    │  NULL │
│ Company      │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Address      │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ City         │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ State        │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Country      │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ PostalCode   │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Phone        │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Fax          │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Email        │ VARCHAR     │ NO      │ NULL    │ NULL    │  NULL │
│ SupportRepId │ BIGINT      │ YES     │ NULL    │ NULL    │  NULL │
├──────────────┴─────────────┴─────────┴─────────┴─────────┴───────┤
│ 13 rows                                                6 columns │
└──────────────────────────────────────────────────────────────────┘

# 2.&nbsp;Agreggation

## Q1

In [ ]:
%config SqlMagic.displaycon = False

In [ ]:
%%sql
SELECT
  COUNT(CustomerId) AS unique_cust_cnt
FROM
  customers;

   unique_cust_cnt
0               59

In [ ]:
%%sql
SELECT
  COUNT(*) AS row_cnt
FROM
  customers;

   row_cnt
0       59

In [ ]:
%%sql
SELECT
  COUNT(country) AS country_cnt
FROM
  customers;

   country_cnt
0           59

In [ ]:
%%sql
SELECT
  country,
  COUNT(CustomerId) AS unique_cust_per_country
FROM
  customers
GROUP BY
  country;

           Country  unique_cust_per_country
0           Brazil                        5
1          Germany                        4
2           Canada                        8
3           Norway                        1
4   Czech Republic                        2
5          Austria                        1
6          Belgium                        1
7          Denmark                        1
8              USA                       13
9         Portugal                        2
10          France                        5
11         Finland                        1
12         Hungary                        1
13         Ireland                        1
14           Italy                        1
15     Netherlands                        1
16          Poland                        1
17           Spain                        1
18          Sweden                        1
19  United Kingdom                        3
20       Australia                        1
21       Argentina                        1
22           Chile                        1
23           India                        2

## Q2

In [ ]:
%%sql
SELECT
  country,
  COUNT(CustomerId) AS unique_cust_per_country
FROM
  customers
GROUP BY
  country
ORDER BY
  unique_cust_per_country DESC
LIMIT
  5;

   Country  unique_cust_per_country
0      USA                       13
1   Canada                        8
2   Brazil                        5
3   France                        5
4  Germany                        4

## Q3

In [ ]:
conn.sql('SHOW ALL TABLES')

┌──────────┬─────────┬─────────────────┬──────────────────────┬────────────────────────────────────────────┬───────────┐
│ database │ schema  │      name       │     column_names     │                column_types                │ temporary │
│ varchar  │ varchar │     varchar     │      varchar[]       │                 varchar[]                  │  boolean  │
├──────────┼─────────┼─────────────────┼──────────────────────┼────────────────────────────────────────────┼───────────┤
│ chinook  │ main    │ albums          │ [AlbumId, Title, A…  │ [BIGINT, VARCHAR, BIGINT]                  │ false     │
│ chinook  │ main    │ artists         │ [ArtistId, Name]     │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ customers       │ [CustomerId, First…  │ [BIGINT, VARCHAR, VARCHAR, VARCHAR, VARC…  │ false     │
│ chinook  │ main    │ employees       │ [EmployeeId, LastN…  │ [BIGINT, VARCHAR, VARCHAR, VARCHAR, BIGI…  │ false     │
│ chinook  │ main    │ genres          │ [GenreId, Name]      │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ invoice_items   │ [InvoiceLineId, In…  │ [BIGINT, BIGINT, BIGINT, DOUBLE, BIGINT]   │ false     │
│ chinook  │ main    │ invoices        │ [InvoiceId, Custom…  │ [BIGINT, BIGINT, TIMESTAMP, VARCHAR, VAR…  │ false     │
│ chinook  │ main    │ media_types     │ [MediaTypeId, Name]  │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ playlist_track  │ [PlaylistId, Track…  │ [BIGINT, BIGINT]                           │ false     │
│ chinook  │ main    │ playlists       │ [PlaylistId, Name]   │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ sqlite_sequence │ [name, seq]          │ [BLOB, BLOB]                               │ false     │
│ chinook  │ main    │ sqlite_stat1    │ [tbl, idx, stat]     │ [BLOB, BLOB, BLOB]                         │ false     │
│ chinook  │ main    │ tracks          │ [TrackId, Name, Al…  │ [BIGINT, VARCHAR, BIGINT, BIGINT, BIGINT…  │ false     │
├──────────┴─────────┴─────────────────┴──────────────────────┴────────────────────────────────────────────┴───────────┤
│ 13 rows                                                                                                    6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [ ]:
conn.sql('DESCRIBE invoices')

┌───────────────────┬─────────────┬─────────┬─────────┬─────────┬───────┐
│    column_name    │ column_type │  null   │   key   │ default │ extra │
│      varchar      │   varchar   │ varchar │ varchar │ varchar │ int32 │
├───────────────────┼─────────────┼─────────┼─────────┼─────────┼───────┤
│ InvoiceId         │ BIGINT      │ NO      │ NULL    │ NULL    │  NULL │
│ CustomerId        │ BIGINT      │ NO      │ NULL    │ NULL    │  NULL │
│ InvoiceDate       │ TIMESTAMP   │ NO      │ NULL    │ NULL    │  NULL │
│ BillingAddress    │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ BillingCity       │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ BillingState      │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ BillingCountry    │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ BillingPostalCode │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Total             │ DOUBLE      │ NO      │ NULL    │ NULL    │  NULL │
└───────────────────┴─────────────┴─────────┴─────────┴─────────┴───────┘

In [ ]:
%%sql
SELECT * FROM invoices LIMIT 10;

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,1.98
1,2,4,2009-01-02,Ullevålsveien 14,Oslo,NaN,Norway,0171,3.96
2,3,8,2009-01-03,Grétrystraat 63,Brussels,NaN,Belgium,1000,5.94
3,4,14,2009-01-06,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2009-01-11,69 Salem Street,Boston,MA,USA,2113,13.86
5,6,37,2009-01-19,Berger Straße 10,Frankfurt,NaN,Germany,60316,0.99
6,7,38,2009-02-01,Barbarossastraße 19,Berlin,NaN,Germany,10779,1.98
7,8,40,2009-02-01,"8, Rue Hanovre",Paris,NaN,France,75002,1.98
8,9,42,2009-02-02,"9, Place Louis Barthou",Bordeaux,NaN,France,33000,3.96
9,10,46,2009-02-03,3 Chatham Street,Dublin,Dublin,Ireland,NaN,5.94

In [ ]:
%%sql
SELECT
  COUNT(*) AS row_cnt,
  COUNT(BillingCity) AS bill_city_count
FROM
  invoices;

   row_cnt  bill_city_count
0      412              412

In [ ]:
%%sql
WITH invoices_date_breakdown_2013 AS (
  SELECT
    InvoiceId,
    InvoiceDate,
    DATE_PART('year', InvoiceDate) AS year,
    DATE_PART('month', InvoiceDate) AS month,
    BillingCity,
    Total
  FROM
    invoices
  WHERE
    DATE_PART('year', InvoiceDate) = 2013
),

agg_per_month_2013 AS (
  SELECT
    BillingCity,
    month,
    SUM(Total) AS total_per_month_2013
  FROM
    invoices_date_breakdown_2013
  GROUP BY
    BillingCity,
    month
  ORDER BY
    BillingCity ASC,
    month ASC
)

SELECT * FROM agg_per_month_2013

    BillingCity  month  total_per_month_2013
0     Amsterdam      8                  1.98
1     Amsterdam      9                 13.86
2      Bordeaux     11                  1.98
3        Boston     12                  1.98
4      Brussels      7                  1.98
..          ...    ...                   ...
74       Warsaw      4                  0.99
75     Winnipeg      2                  0.99
76  Yellowknife      2                  1.98
77  Yellowknife      6                  3.96
78  Yellowknife      9                  5.94

[79 rows x 3 columns]

# 3.&nbsp; JOINS

In [ ]:
conn.sql('SHOW ALL TABLES')

┌──────────┬─────────┬─────────────────┬──────────────────────┬────────────────────────────────────────────┬───────────┐
│ database │ schema  │      name       │     column_names     │                column_types                │ temporary │
│ varchar  │ varchar │     varchar     │      varchar[]       │                 varchar[]                  │  boolean  │
├──────────┼─────────┼─────────────────┼──────────────────────┼────────────────────────────────────────────┼───────────┤
│ chinook  │ main    │ albums          │ [AlbumId, Title, A…  │ [BIGINT, VARCHAR, BIGINT]                  │ false     │
│ chinook  │ main    │ artists         │ [ArtistId, Name]     │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ customers       │ [CustomerId, First…  │ [BIGINT, VARCHAR, VARCHAR, VARCHAR, VARC…  │ false     │
│ chinook  │ main    │ employees       │ [EmployeeId, LastN…  │ [BIGINT, VARCHAR, VARCHAR, VARCHAR, BIGI…  │ false     │
│ chinook  │ main    │ genres          │ [GenreId, Name]      │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ invoice_items   │ [InvoiceLineId, In…  │ [BIGINT, BIGINT, BIGINT, DOUBLE, BIGINT]   │ false     │
│ chinook  │ main    │ invoices        │ [InvoiceId, Custom…  │ [BIGINT, BIGINT, TIMESTAMP, VARCHAR, VAR…  │ false     │
│ chinook  │ main    │ media_types     │ [MediaTypeId, Name]  │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ playlist_track  │ [PlaylistId, Track…  │ [BIGINT, BIGINT]                           │ false     │
│ chinook  │ main    │ playlists       │ [PlaylistId, Name]   │ [BIGINT, VARCHAR]                          │ false     │
│ chinook  │ main    │ sqlite_sequence │ [name, seq]          │ [BLOB, BLOB]                               │ false     │
│ chinook  │ main    │ sqlite_stat1    │ [tbl, idx, stat]     │ [BLOB, BLOB, BLOB]                         │ false     │
│ chinook  │ main    │ tracks          │ [TrackId, Name, Al…  │ [BIGINT, VARCHAR, BIGINT, BIGINT, BIGINT…  │ false     │
├──────────┴─────────┴─────────────────┴──────────────────────┴────────────────────────────────────────────┴───────────┤
│ 13 rows                                                                                                    6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [ ]:
conn.sql('DESCRIBE customers')

┌──────────────┬─────────────┬─────────┬─────────┬─────────┬───────┐
│ column_name  │ column_type │  null   │   key   │ default │ extra │
│   varchar    │   varchar   │ varchar │ varchar │ varchar │ int32 │
├──────────────┼─────────────┼─────────┼─────────┼─────────┼───────┤
│ CustomerId   │ BIGINT      │ NO      │ NULL    │ NULL    │  NULL │
│ FirstName    │ VARCHAR     │ NO      │ NULL    │ NULL    │  NULL │
│ LastName     │ VARCHAR     │ NO      │ NULL    │ NULL    │  NULL │
│ Company      │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Address      │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ City         │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ State        │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Country      │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ PostalCode   │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Phone        │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Fax          │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Email        │ VARCHAR     │ NO      │ NULL    │ NULL    │  NULL │
│ SupportRepId │ BIGINT      │ YES     │ NULL    │ NULL    │  NULL │
├──────────────┴─────────────┴─────────┴─────────┴─────────┴───────┤
│ 13 rows                                                6 columns │
└──────────────────────────────────────────────────────────────────┘

In [ ]:
conn.sql('DESCRIBE employees')

┌─────────────┬─────────────┬─────────┬─────────┬─────────┬───────┐
│ column_name │ column_type │  null   │   key   │ default │ extra │
│   varchar   │   varchar   │ varchar │ varchar │ varchar │ int32 │
├─────────────┼─────────────┼─────────┼─────────┼─────────┼───────┤
│ EmployeeId  │ BIGINT      │ NO      │ NULL    │ NULL    │  NULL │
│ LastName    │ VARCHAR     │ NO      │ NULL    │ NULL    │  NULL │
│ FirstName   │ VARCHAR     │ NO      │ NULL    │ NULL    │  NULL │
│ Title       │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ ReportsTo   │ BIGINT      │ YES     │ NULL    │ NULL    │  NULL │
│ BirthDate   │ TIMESTAMP   │ YES     │ NULL    │ NULL    │  NULL │
│ HireDate    │ TIMESTAMP   │ YES     │ NULL    │ NULL    │  NULL │
│ Address     │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ City        │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ State       │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Country     │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ PostalCode  │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Phone       │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Fax         │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
│ Email       │ VARCHAR     │ YES     │ NULL    │ NULL    │  NULL │
├─────────────┴─────────────┴─────────┴─────────┴─────────┴───────┤
│ 15 rows                                               6 columns │
└─────────────────────────────────────────────────────────────────┘

In [ ]:
%%sql
SELECT
  c.CustomerId,
  CONCAT(c.FirstName, ' ', c.LastName) AS cust_name,
  e.EmployeeId,
  CONCAT(e.FirstName, ' ', e.LastName) AS employee_name
FROM
  customers c
LEFT JOIN
  employees e
ON
  c.SupportRepId = e.EmployeeId;

    CustomerId              cust_name  EmployeeId  employee_name
0            1         Luís Gonçalves           3   Jane Peacock
1            2          Leonie Köhler           5  Steve Johnson
2            3      François Tremblay           3   Jane Peacock
3            4           Bjørn Hansen           4  Margaret Park
4            5  František Wichterlová           4  Margaret Park
5            6            Helena Holý           5  Steve Johnson
6            7          Astrid Gruber           5  Steve Johnson
7            8           Daan Peeters           4  Margaret Park
8            9           Kara Nielsen           4  Margaret Park
9           10        Eduardo Martins           4  Margaret Park
10          11        Alexandre Rocha           5  Steve Johnson
11          12        Roberto Almeida           3   Jane Peacock
12          13         Fernanda Ramos           4  Margaret Park
13          14           Mark Philips           5  Steve Johnson
14          15      Jennifer Peterson           3   Jane Peacock
15          16           Frank Harris           4  Margaret Park
16          17             Jack Smith           5  Steve Johnson
17          18        Michelle Brooks           3   Jane Peacock
18          19              Tim Goyer           3   Jane Peacock
19          20             Dan Miller           4  Margaret Park
20          21            Kathy Chase           5  Steve Johnson
21          22        Heather Leacock           4  Margaret Park
22          23            John Gordon           4  Margaret Park
23          24          Frank Ralston           3   Jane Peacock
24          25         Victor Stevens           5  Steve Johnson
25          26     Richard Cunningham           4  Margaret Park
26          27           Patrick Gray           4  Margaret Park
27          28          Julia Barnett           5  Steve Johnson
28          29           Robert Brown           3   Jane Peacock
29          30         Edward Francis           3   Jane Peacock
30          31            Martha Silk           5  Steve Johnson
31          32         Aaron Mitchell           4  Margaret Park
32          33         Ellie Sullivan           3   Jane Peacock
33          34         João Fernandes           4  Margaret Park
34          35       Madalena Sampaio           4  Margaret Park
35          36       Hannah Schneider           5  Steve Johnson
36          37        Fynn Zimmermann           3   Jane Peacock
37          38        Niklas Schröder           3   Jane Peacock
38          39        Camille Bernard           4  Margaret Park
39          40     Dominique Lefebvre           4  Margaret Park
40          41            Marc Dubois           5  Steve Johnson
41          42           Wyatt Girard           3   Jane Peacock
42          43       Isabelle Mercier           3   Jane Peacock
43          44       Terhi Hämäläinen           3   Jane Peacock
44          45        Ladislav Kovács           3   Jane Peacock
45          46          Hugh O'Reilly           3   Jane Peacock
46          47          Lucas Mancini           5  Steve Johnson
47          48  Johannes Van der Berg           5  Steve Johnson
48          49       Stanisław Wójcik           4  Margaret Park
49          50          Enrique Muñoz           5  Steve Johnson
50          51       Joakim Johansson           5  Steve Johnson
51          52             Emma Jones           3   Jane Peacock
52          53            Phil Hughes           3   Jane Peacock
53          54           Steve Murray           5  Steve Johnson
54          55            Mark Taylor           4  Margaret Park
55          56        Diego Gutiérrez           4  Margaret Park
56          57             Luis Rojas           5  Steve Johnson
57          58           Manoj Pareek           3   Jane Peacock
58          59        Puja Srivastava           3   Jane Peacock

In [ ]:
%%sql
WITH cust_employee_pair AS (
  SELECT
    c.CustomerId,
    CONCAT(c.FirstName, ' ', c.LastName) AS cust_name,
    e.EmployeeId,
    CONCAT(e.FirstName, ' ', e.LastName) AS employee_name
  FROM
    customers c
  LEFT JOIN
    employees e
  ON
    c.SupportRepId = e.EmployeeId
)

SELECT
  EmployeeId,
  employee_name,
  COUNT(CustomerId) AS cust_cnt
FROM
  cust_employee_pair
GROUP BY
  EmployeeId, employee_name

   EmployeeId  employee_name  cust_cnt
0           3   Jane Peacock        21
1           5  Steve Johnson        18
2           4  Margaret Park        20

In [ ]:
%%sql
SELECT COUNT(EmployeeId) FROM employees

   count(EmployeeId)
0                  8